### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by arshaver**
Remove mention of ESP8266 configTime method bug which has been fixed.

### CODE REVIEW

**Comment by vlastahajek** [comment]
@arshaver, thanks for the PR. The bug was fixed, but there was not any release with it yet.

**Comment by arshaver** [comment]
Got it, thanks.

**Comment by vlastahajek** [comment]
Friend, you didn't need to close this, we can wait for the new release of ESP8266 SDK ;)

**Comment by arshaver** [comment]
Apologies, my first PR.

**Pull request merged**
