### PR TITLE
Ci test unit

### PR DESCRIPTION
**Pull request by hpsaturn**
## Proposed Changes

Added a complete CI workflow for test the two architectures ESP32 and ESP8266 with a CI over PlatformIO on GitHub Workflows (Actions)

## Checklist

- [x] added PlatformIO basic example (Influx Basic Write)
- [x] tested example using PlatformIO
- [x] added global platformio ini file for test the complete library on ESP32 and ESP8266
- [x] added workflow for Github usin CI over Python and PlatformIO
- [x] added badge on README for success CI test on master branch 
- [x] tested with the current commint before the PR

## How to test the library (locally)

In the root directory of the library only type:

```bash
pio run
``` 
It is only for local tests, after the merge of this PR, Github workflow will doing that alone for you :D

## Badge

The badge only will be works after this PR, but a little preview is possible in my project [CanAirIO](https://github.com/kike-canaries/canairio_firmware)

### CODE REVIEW

**Comment by vlastahajek** [comment]
Thanks for this PR. Having checking build in CI is also on my TODO list, 
It seems having copied example for PlatformIO look a bit redundant. Is it possible, to have the same example for Arduino IDE and PlatformIO. E.g. to somehow persuade PlatformIO to compile a `.ino` file?

**Comment by hpsaturn** [comment]
Nop, this is the reason why I did it, the ino file is possible build with a simple platformio.ini file in the same directory, and works fine, but the problems is that with CI it doesn't works well when you need extend a different architectures. I could do a commit changes for that but I dont recommended it. What do you want?

**Comment by vlastahajek** [comment]
For now, I think, this PR makes a great addition. We can change some details later. Thanks.

**Comment by vlastahajek** [comment]
FYI. I changed POI config that it will build tests. It is better because tests cover complete API and there is no need to have the additional example.

**Pull request merged**
